### ISSUE TITLE
Assign a led to PC13

### ISSUE THREAD

**Issue by ivand58** [Palmitoxico/STM32F103C8T6-Examples#1]
Could you pls add the pulse to the PC13 as well?

In some boards the LED is connected to port C13.

**Comment by augustofg** [comment]
This wouldn't work. As stated in the 171 and 172 pages of the STM32F103xx Reference Manual you have the registers `GPIOx_CRL` for the port pins 0 to 7 and `GPIOx_CRH` for the port pins 8 to 15. Each nibble of the `GPIOx_CRx` registers corresponds to one pin of the respective port. So to you configure the PC13 pin as output you would need do this:

```
// Enable the PORTC and Alternate Function clocks
RCC->APB2ENR |= RCC_APB2ENR_IOPCEN | RCC_APB2ENR_AFIOEN;

// Configure pin PC13 as push-pull output with 2 MHz max speed
GPIOA->CRH |= 0x00200000;
```

Reference manual:
[http://www.st.com/content/ccc/resource/technical/document/reference_manual/59/b9/ba/7f/11/af/43/d5/CD00171190.pdf/files/CD00171190.pdf/jcr:content/translations/en.CD00171190.pdf](url)

**Comment by Designer-Rick** [comment]
GPIOC->CRH |= 0x00200000;

**Comment by augustofg** [comment]
Yes @Designer-Rick . I wrote GPIOA by mistake.
