### ISSUE TITLE
Example_GPIO and other all projects also given link below.https://github.com/avislab/STM32F103

### ISSUE THREAD

**Issue by bonakurthihari** [Palmitoxico/STM32F103C8T6-Examples#3]
Sir. this is the link actually i have seen stm32 examples in github in master zip file., but in the project .coproj file format is not supporting. can you please tell me which ide tool is support this .coproj file format.
link: https://github.com/avislab/STM32F103

**Comment by augustofg** [comment]
These are Eclipse projects. The examples provided in my repository doesn't require IDEs and doesn't rely on the ST's HAL library.

You can try contact the owner of the repository you mentioned for further doubts. I'm closing this issue as it isn't related to my repository.
